import { describe, it, expect } from 'vitest'
import { parse23andMeFileAsync } from '../23andme'
import { TWENTYTHREEANDME_SAMPLE } from '../../__tests__/fixtures'

describe('parse23andMeFileAsync', () => {
  it('should parse valid 23andMe file with all metadata', async () => {
    const result = await parse23andMeFileAsync(TWENTYTHREEANDME_SAMPLE, 1)

    expect(result.snps).toHaveLength(7)
    expect(result.errors).toHaveLength(0)
    expect(result.format).toBe('23andme')
    expect(result.metadata).toBeDefined()
    expect(result.metadata?.fileId).toBe('1234567890abcdef')
    expect(result.metadata?.signature).toBe('abc123def456')
    expect(result.metadata?.timestamp).toBe('2026-01-25T08:00:00Z')
  })

  it('should handle single-character genotypes for hemizygous regions', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	X	100	A
rs2	Y	200	T
rs3	MT	300	C`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(3)
    expect(result.snps[0].genotype).toBe('A')
    expect(result.snps[1].genotype).toBe('T')
    expect(result.snps[2].genotype).toBe('C')
    expect(result.snps[0].chromosome).toBe('X')
    expect(result.snps[1].chromosome).toBe('Y')
    expect(result.snps[2].chromosome).toBe('MT')
  })

  it('should handle two-character genotypes for autosomes', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	1	100	AT
rs2	2	200	CG
rs3	22	300	GG`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(3)
    expect(result.snps[0].genotype).toBe('AT')
    expect(result.snps[1].genotype).toBe('CG')
    expect(result.snps[2].genotype).toBe('GG')
  })

  it('should skip invalid chromosomes', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	1	100	AT
rs2	99	200	CG
rs3	22	300	GG`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(2)
    expect(result.errors).toHaveLength(1)
    expect(result.errors[0].reason).toContain('Invalid chromosome: 99')
  })

  it('should skip invalid genotypes', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	1	100	AT
rs2	1	200	XY
rs3	22	300	GG`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(2)
    expect(result.errors).toHaveLength(1)
    expect(result.errors[0].reason).toContain('Invalid genotype: XY')
  })

  it('should extract metadata from header', async () => {
    const content = `# This data file is generated by 23andMe.
# file_id: test123
# signature: sig456
# timestamp: 2026-01-25T12:00:00Z
# rsid	chromosome	position	genotype
rs1	1	100	AT`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.metadata?.fileId).toBe('test123')
    expect(result.metadata?.signature).toBe('sig456')
    expect(result.metadata?.timestamp).toBe('2026-01-25T12:00:00Z')
  })

  it('should handle missing values', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	1	100	--
rs2	X	200	-
rs3	1	300	00
rs4	X	400	0`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(4)
    expect(result.snps[0].genotype).toBe('--')
    expect(result.snps[1].genotype).toBe('-')
    expect(result.snps[2].genotype).toBe('00')
    expect(result.snps[3].genotype).toBe('0')
  })

  it('should handle single D and I genotypes for indels', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
i706723	MT	3307	D
i123456	X	1000	I
i789012	Y	2000	D`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(3)
    expect(result.snps[0].rsid).toBe('i706723')
    expect(result.snps[0].chromosome).toBe('MT')
    expect(result.snps[0].position).toBe('3307')
    expect(result.snps[0].genotype).toBe('D')
    expect(result.snps[1].genotype).toBe('I')
    expect(result.snps[2].genotype).toBe('D')
  })

  it('should handle internal IDs starting with i', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	1	100	AT
i720493	22	200	CG
i123456	1	300	GG`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(3)
    expect(result.snps[1].rsid).toBe('i720493')
    expect(result.snps[2].rsid).toBe('i123456')
  })

  it('should handle large files with batching', async () => {
    const header = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
`
    const snpLines = Array.from({ length: 10000 }, (_, i) => `rs${i}\t1\t${1000 + i}\tAT`).join(
      '\n'
    )
    const largeFile = header + snpLines

    const result = await parse23andMeFileAsync(largeFile, 1)

    expect(result.snps).toHaveLength(10000)
    expect(result.format).toBe('23andme')
    expect(result.errors).toHaveLength(0)
  })

  it('should report progress', async () => {
    const header = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
`
    const snpLines = Array.from({ length: 6000 }, (_, i) => `rs${i}\t1\t${1000 + i}\tAT`).join('\n')
    const largeFile = header + snpLines

    const progressValues: number[] = []
    await parse23andMeFileAsync(largeFile, 1, progress => {
      progressValues.push(progress)
    })

    expect(progressValues.length).toBeGreaterThan(0)
    expect(progressValues[progressValues.length - 1]).toBeLessThanOrEqual(99)
  })

  it('should collect errors with line numbers', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	1	100	AT
rs2	99	200	CG
rs3	1	300	XY
rs4	22	400	GG`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.errors).toHaveLength(2)
    expect(result.errors[0].lineNumber).toBe(4)
    expect(result.errors[0].reason).toContain('Invalid chromosome')
    expect(result.errors[1].lineNumber).toBe(5)
    expect(result.errors[1].reason).toContain('Invalid genotype')
  })

  it('should handle missing metadata gracefully', async () => {
    const content = `# rsid	chromosome	position	genotype
rs1	1	100	AT
rs2	22	200	CG`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(2)
    expect(result.metadata).toBeUndefined()
  })

  it('should handle insufficient columns', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	1	100	AT
rs2	1	200
rs3	22	300	GG`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(2)
    expect(result.errors).toHaveLength(1)
    expect(result.errors[0].reason).toContain('Insufficient columns')
  })

  it('should skip empty lines', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype

rs1	1	100	AT

rs2	22	200	CG

`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(2)
    expect(result.errors).toHaveLength(0)
  })

  it('should normalize chromosomes to uppercase', async () => {
    const content = `# This data file is generated by 23andMe.
# rsid	chromosome	position	genotype
rs1	x	100	A
rs2	y	200	T
rs3	mt	300	C`

    const result = await parse23andMeFileAsync(content, 1)

    expect(result.snps).toHaveLength(3)
    expect(result.snps[0].chromosome).toBe('X')
    expect(result.snps[1].chromosome).toBe('Y')
    expect(result.snps[2].chromosome).toBe('MT')
  })
})
