import type { SNP } from '../types'

export function generateAncestryCsv(snps: SNP[]): string {
  const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC'

  let tsv = `#AncestryDNA merged data
#Generated by MergeDNA at: ${timestamp}
#Merged from 2 files
#THIS INFORMATION IS FOR YOUR PERSONAL USE AND IS INTENDED FOR GENEALOGICAL RESEARCH ONLY.
rsid\tchromosome\tposition\tallele1\tallele2
`

  snps.forEach(snp => {
    // Convert MyHeritage letter format to Ancestry numeric format
    let chromosome = snp.chromosome
    if (chromosome === 'X') chromosome = '23'
    else if (chromosome === 'Y') chromosome = '24'
    else if (chromosome === 'XY') chromosome = '25'
    else if (chromosome === 'MT') chromosome = '26'

    // Handle single-character genotypes (from 23andMe) - should be normalized already,
    // but double-check for safety
    const genotype = snp.genotype.length === 1 ? snp.genotype + snp.genotype : snp.genotype
    const allele1 = genotype[0] || ''
    const allele2 = genotype[1] || ''
    tsv += `${snp.rsid}\t${chromosome}\t${snp.position}\t${allele1}\t${allele2}\n`
  })

  return tsv
}
