import { describe, it, expect } from 'vitest'
import {
  detectFormat,
  validateGenotype,
  parseAncestryFile,
  parseMyHeritageFile,
  parseLivingDNAFile,
  parseAncestryFileAsync,
  parseMyHeritageFileAsync,
  parseLivingDNAFileAsync,
  mergeSnps,
  mergeSnpsAsync,
  generateMyHeritageCsv,
  generateAncestryTsv,
  generateLogFile,
  normalizeGenotypeForFormat,
} from './dnaParser'

const ANCESTRY_SAMPLE = `#AncestryDNA raw data download
#This file was generated by AncestryDNA at: 01/17/2026 16:39:45 UTC
rsid	chromosome	position	allele1	allele2
rs3131972	1	752721	G	G
rs114525117	1	759036	G	G
rs11240777	1	798959	G	G
rs4475691	1	846808	T	C
rs7537756	1	854250	A	G`

const MYHERITAGE_SAMPLE = `##fileformat=MyHeritage
##format=MHv1.0
##chip=GSA
RSID,CHROMOSOME,POSITION,RESULT
"rs3131972","1","752721","GG"
"rs114525117","1","759036","GG"
"rs11240777","1","798959","GG"
"rs4475691","1","846808","CT"
"rs2341354","1","918573","AG"`

const LIVINGDNA_SAMPLE = `# Living DNA customer genotype data download file version: 1.1.0
# File creation date: 1-24-2025
# Genotype chip: Sirius
# The content of this file is subject to updates and changes depending on the time of download.
# Human Genome Reference Build 37 (GRCh37.p13).
# Genotypes are presented on the forward strand.
#
# rsid	chromosome	position	genotype
rs3131972	1	752721	AG
rs114525117	1	759036	GG
rs141175086	1	780397	CC
AX-33748877	22	51162850	CT
rs143357798	22	51193012	CC`

describe('detectFormat', () => {
  it('should detect Ancestry format from sample file', () => {
    expect(detectFormat(ANCESTRY_SAMPLE)).toBe('ancestry')
  })

  it('should detect MyHeritage format from sample file', () => {
    expect(detectFormat(MYHERITAGE_SAMPLE)).toBe('myheritage')
  })

  it('should detect LivingDNA format from sample file', () => {
    expect(detectFormat(LIVINGDNA_SAMPLE)).toBe('livingdna')
  })

  it('should return unknown for empty content', () => {
    expect(detectFormat('')).toBe('unknown')
  })

  it('should return unknown for invalid format', () => {
    expect(detectFormat('random text\nno valid format')).toBe('unknown')
  })
})

describe('validateGenotype', () => {
  it('should validate standard nucleotide pairs', () => {
    expect(validateGenotype('AA')).toBe(true)
    expect(validateGenotype('AT')).toBe(true)
    expect(validateGenotype('CG')).toBe(true)
    expect(validateGenotype('TT')).toBe(true)
  })

  it('should validate special markers (lenient mode)', () => {
    expect(validateGenotype('--')).toBe(true)
    expect(validateGenotype('00')).toBe(true)
    expect(validateGenotype('DD')).toBe(true)
    expect(validateGenotype('II')).toBe(true)
  })

  it('should reject invalid genotypes', () => {
    expect(validateGenotype('XY')).toBe(false)
    expect(validateGenotype('ZZ')).toBe(false)
    expect(validateGenotype('12')).toBe(false)
    expect(validateGenotype('A')).toBe(false)
  })

  it('should be case insensitive', () => {
    expect(validateGenotype('aa')).toBe(true)
    expect(validateGenotype('Tc')).toBe(true)
  })

  it('should validate DI and ID genotypes', () => {
    expect(validateGenotype('DI')).toBe(true)
    expect(validateGenotype('ID')).toBe(true)
    expect(validateGenotype('di')).toBe(true)
    expect(validateGenotype('id')).toBe(true)
  })
})

describe('parseAncestryFile', () => {
  it('should parse Ancestry format correctly', () => {
    const result = parseAncestryFile(ANCESTRY_SAMPLE, 1)

    expect(result.format).toBe('ancestry')
    expect(result.snps).toHaveLength(5)
    expect(result.errors).toHaveLength(0)

    expect(result.snps[0]).toEqual({
      rsid: 'rs3131972',
      chromosome: '1',
      position: '752721',
      genotype: 'GG',
      sourceFile: 1,
    })
  })

  it('should skip comment lines and header', () => {
    const result = parseAncestryFile(ANCESTRY_SAMPLE, 1)
    expect(result.snps.every(snp => !snp.rsid.startsWith('#'))).toBe(true)
  })

  it('should handle invalid rows', () => {
    const invalidData = `rsid	chromosome	position	allele1	allele2
rs123	1	100	X	Y
rs456	1	200	A	A`

    const result = parseAncestryFile(invalidData, 1)
    expect(result.snps).toHaveLength(1)
    expect(result.errors).toHaveLength(1)
    expect(result.errors[0].reason).toContain('Invalid genotype')
  })

  it('should handle missing columns', () => {
    const invalidData = `rsid	chromosome	position
rs123	1`

    const result = parseAncestryFile(invalidData, 1)
    expect(result.errors.length).toBeGreaterThan(0)
  })

  it('should reject invalid chromosomes for Ancestry format', () => {
    const invalidData = `rsid	chromosome	position	allele1	allele2
rs789	99	300	C	C
rs000	0	400	A	A`

    const result = parseAncestryFile(invalidData, 1)
    expect(result.snps).toHaveLength(0)
    expect(result.errors).toHaveLength(2)
    expect(result.errors[0].reason).toContain('Invalid chromosome: 99')
    expect(result.errors[1].reason).toContain('Invalid chromosome: 0')
  })

  it('should accept valid chromosomes 1-22, X, Y, MT and normalize Ancestry 23-26', () => {
    const validData = `rsid	chromosome	position	allele1	allele2
rs1	1	100	A	A
rs22	22	200	T	T
rs23	23	300	C	C
rs24	24	400	G	G
rs25	25	500	A	A
rs26	26	600	T	T
rsX	X	700	C	C
rsY	Y	800	G	G
rsMT	MT	900	A	A`

    const result = parseAncestryFile(validData, 1)
    expect(result.snps).toHaveLength(9)
    expect(result.errors).toHaveLength(0)

    // Check that Ancestry numeric chromosomes are kept as-is
    const chr23 = result.snps.find(s => s.rsid === 'rs23')
    const chr24 = result.snps.find(s => s.rsid === 'rs24')
    const chr25 = result.snps.find(s => s.rsid === 'rs25')
    const chr26 = result.snps.find(s => s.rsid === 'rs26')

    expect(chr23?.chromosome).toBe('23') // X chromosome in Ancestry format
    expect(chr24?.chromosome).toBe('24') // Y chromosome in Ancestry format
    expect(chr25?.chromosome).toBe('25') // PAR region in Ancestry format
    expect(chr26?.chromosome).toBe('26') // MT chromosome in Ancestry format
  })
})

describe('parseMyHeritageFile', () => {
  it('should parse MyHeritage format correctly', () => {
    const result = parseMyHeritageFile(MYHERITAGE_SAMPLE, 1)

    expect(result.format).toBe('myheritage')
    expect(result.snps).toHaveLength(5)
    expect(result.errors).toHaveLength(0)

    expect(result.snps[0]).toEqual({
      rsid: 'rs3131972',
      chromosome: '1',
      position: '752721',
      genotype: 'GG',
      sourceFile: 1,
    })
  })

  it('should handle quoted CSV values', () => {
    const result = parseMyHeritageFile(MYHERITAGE_SAMPLE, 1)
    expect(result.snps[0].rsid).toBe('rs3131972')
    expect(result.snps[0].genotype).toBe('GG')
  })
})

describe('mergeSnps', () => {
  const defaultOptions = { preferredFile: 1 as const, fillMissing: true }

  it('should merge SNPs from two files without duplicates', () => {
    const file1 = parseAncestryFile(ANCESTRY_SAMPLE, 1)
    const file2 = parseMyHeritageFile(MYHERITAGE_SAMPLE, 2)

    const result = mergeSnps(file1.snps, file2.snps, defaultOptions)

    expect(result.mergedSnps.length).toBeGreaterThan(0)
    expect(result.mergedSnps.length).toBeLessThanOrEqual(file1.snps.length + file2.snps.length)
  })

  it('should detect conflicts when same RSID has different genotypes', () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AA', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AC', sourceFile: 2 as const },
    ]

    const result = mergeSnps(file1Snps, file2Snps, defaultOptions)

    expect(result.conflicts).toHaveLength(1)
    expect(result.conflicts[0].file1Genotype).toBe('AA')
    expect(result.conflicts[0].file2Genotype).toBe('AC')
    expect(result.conflicts[0].chosenGenotype).toBe('AA')
    expect(result.conflicts[0].resolutionReason).toBe('Preferred File 1')
  })

  it('should prioritize Ancestry when preferred', () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AA', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AC', sourceFile: 2 as const },
    ]

    const result = mergeSnps(file1Snps, file2Snps, { preferredFile: 1, fillMissing: false })

    const mergedSnp = result.mergedSnps.find(s => s.rsid === 'rs123')
    expect(mergedSnp?.genotype).toBe('AA')
    expect(result.conflicts[0].resolutionReason).toBe('Preferred File 1')
  })

  it('should prioritize MyHeritage when preferred', () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AA', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AC', sourceFile: 2 as const },
    ]

    const result = mergeSnps(file1Snps, file2Snps, { preferredFile: 2, fillMissing: false })

    const mergedSnp = result.mergedSnps.find(s => s.rsid === 'rs123')
    expect(mergedSnp?.genotype).toBe('AC')
    expect(result.conflicts[0].resolutionReason).toBe('Preferred File 2')
  })

  it('should fill missing values when fillMissing is true', () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: '--', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AC', sourceFile: 2 as const },
    ]

    const result = mergeSnps(file1Snps, file2Snps, { preferredFile: 1, fillMissing: true })

    const mergedSnp = result.mergedSnps.find(s => s.rsid === 'rs123')
    expect(mergedSnp?.genotype).toBe('AC')
    expect(result.conflicts[0].resolutionReason).toBe('Filled Missing from File 2')
  })

  it('should not fill missing values when fillMissing is false', () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: '--', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AC', sourceFile: 2 as const },
    ]

    const result = mergeSnps(file1Snps, file2Snps, { preferredFile: 1, fillMissing: false })

    const mergedSnp = result.mergedSnps.find(s => s.rsid === 'rs123')
    expect(mergedSnp?.genotype).toBe('--')
    expect(result.conflicts[0].resolutionReason).toBe('Preferred File 1')
  })

  it('should sort by chromosome and position', () => {
    const file1Snps = [
      { rsid: 'rs2', chromosome: '2', position: '200', genotype: 'AA', sourceFile: 1 as const },
      { rsid: 'rs1', chromosome: '1', position: '100', genotype: 'TT', sourceFile: 1 as const },
    ]

    const result = mergeSnps(file1Snps, [], defaultOptions)

    expect(result.mergedSnps[0].rsid).toBe('rs1')
    expect(result.mergedSnps[1].rsid).toBe('rs2')
  })
})

describe('generateMyHeritageCsv', () => {
  it('should generate valid MyHeritage CSV format', () => {
    const snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AA', sourceFile: 1 as const },
    ]

    const result = generateMyHeritageCsv(snps)

    expect(result.csv).toContain('##fileformat=MyHeritage')
    expect(result.csv).toContain('RSID,CHROMOSOME,POSITION,RESULT')
    expect(result.csv).toContain('"rs123","1","100","AA"')
    expect(result.excludedPAR).toBe(0)
  })

  it('should exclude XY (Pseudoautosomal) chromosomes', () => {
    const snps = [
      { rsid: 'rs1', chromosome: 'X', position: '100', genotype: 'AA', sourceFile: 1 as const },
      { rsid: 'rs2', chromosome: 'XY', position: '200', genotype: 'TT', sourceFile: 1 as const },
      { rsid: 'rs3', chromosome: '25', position: '300', genotype: 'CC', sourceFile: 1 as const }, // Ancestry PAR format
      { rsid: 'rs4', chromosome: 'Y', position: '400', genotype: 'GG', sourceFile: 1 as const },
    ]

    const result = generateMyHeritageCsv(snps)

    expect(result.csv).toContain('"rs1"')
    expect(result.csv).not.toContain('"rs2"')
    expect(result.csv).not.toContain('"rs3"')
    expect(result.csv).toContain('"rs4"')
    expect(result.excludedPAR).toBe(2)
  })

  it('should include timestamp in header', () => {
    const result = generateMyHeritageCsv([])
    expect(result.csv).toMatch(/##timestamp=.*UTC/)
  })
})

describe('generateAncestryTsv', () => {
  it('should generate valid Ancestry TXT format', () => {
    const snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AA', sourceFile: 1 as const },
    ]

    const tsv = generateAncestryTsv(snps)

    expect(tsv).toContain('#AncestryDNA merged data')
    expect(tsv).toContain('rsid\tchromosome\tposition\tallele1\tallele2')
    expect(tsv).toContain('rs123\t1\t100\tA\tA')
  })

  it('should convert chromosomes to Ancestry numeric format', () => {
    const snps = [
      { rsid: 'rs1', chromosome: 'X', position: '100', genotype: 'AA', sourceFile: 1 as const },
      { rsid: 'rs2', chromosome: 'Y', position: '200', genotype: 'TT', sourceFile: 1 as const },
      { rsid: 'rs3', chromosome: 'XY', position: '300', genotype: 'CC', sourceFile: 1 as const },
      { rsid: 'rs4', chromosome: 'MT', position: '400', genotype: 'GG', sourceFile: 1 as const },
    ]

    const tsv = generateAncestryTsv(snps)

    expect(tsv).toContain('rs1\t23\t100\tA\tA') // X → 23
    expect(tsv).toContain('rs2\t24\t200\tT\tT') // Y → 24
    expect(tsv).toContain('rs3\t25\t300\tC\tC') // XY → 25
    expect(tsv).toContain('rs4\t26\t400\tG\tG') // MT → 26
  })

  it('should split genotype into two alleles', () => {
    const snps = [
      { rsid: 'rs456', chromosome: '2', position: '200', genotype: 'AC', sourceFile: 1 as const },
    ]

    const tsv = generateAncestryTsv(snps)

    expect(tsv).toContain('rs456\t2\t200\tA\tC')
  })

  it('should include timestamp in header', () => {
    const tsv = generateAncestryTsv([])
    expect(tsv).toMatch(/#Generated by MergeDNA at:.*UTC/)
  })
})

describe('generateLogFile', () => {
  it('should generate log with conflicts and resolution reasons', () => {
    const conflicts = [
      {
        rsid: 'rs123',
        chromosome: '1',
        position: '100',
        file1Genotype: 'AA',
        file2Genotype: 'AC',
        chosenGenotype: 'AA',
        resolutionReason: 'Preferred Ancestry',
      },
    ]

    const log = generateLogFile(conflicts, [])

    expect(log).toContain('DNA Merge Log')
    expect(log).toContain('CONFLICTS')
    expect(log).toContain('rs123')
    expect(log).toContain('Preferred Ancestry')
    expect(log).toContain('Resolution Reason')
  })

  it('should generate log with skipped rows', () => {
    const skipped = [
      {
        lineNumber: 10,
        content: 'invalid line',
        reason: 'Invalid genotype',
        sourceFile: 1 as const,
      },
    ]

    const log = generateLogFile([], skipped)

    expect(log).toContain('SKIPPED ROWS')
    expect(log).toContain('invalid line')
    expect(log).toContain('Invalid genotype')
  })

  it('should include summary counts', () => {
    const conflicts = [
      {
        rsid: 'rs1',
        chromosome: '1',
        position: '100',
        file1Genotype: 'AA',
        file2Genotype: 'AC',
        chosenGenotype: 'AA',
        resolutionReason: 'Preferred Ancestry',
      },
    ]
    const skipped = [{ lineNumber: 1, content: 'bad', reason: 'error', sourceFile: 1 as const }]

    const log = generateLogFile(conflicts, skipped)

    expect(log).toContain('Conflicts detected: 1')
    expect(log).toContain('Invalid rows skipped: 1')
  })
})

describe('normalizeGenotypeForFormat', () => {
  describe('converting to MyHeritage format', () => {
    it('should convert "0 0" to "--"', () => {
      expect(normalizeGenotypeForFormat('0 0', 'myheritage')).toBe('--')
    })

    it('should convert "00" to "--"', () => {
      expect(normalizeGenotypeForFormat('00', 'myheritage')).toBe('--')
    })

    it('should handle whitespace around "0 0"', () => {
      expect(normalizeGenotypeForFormat(' 0 0 ', 'myheritage')).toBe('--')
    })

    it('should handle whitespace around "00"', () => {
      expect(normalizeGenotypeForFormat(' 00 ', 'myheritage')).toBe('--')
    })

    it('should leave other genotypes unchanged', () => {
      expect(normalizeGenotypeForFormat('AA', 'myheritage')).toBe('AA')
      expect(normalizeGenotypeForFormat('AT', 'myheritage')).toBe('AT')
      expect(normalizeGenotypeForFormat('CG', 'myheritage')).toBe('CG')
      expect(normalizeGenotypeForFormat('--', 'myheritage')).toBe('--')
      expect(normalizeGenotypeForFormat('DD', 'myheritage')).toBe('DD')
      expect(normalizeGenotypeForFormat('II', 'myheritage')).toBe('II')
    })
  })

  describe('converting to Ancestry format', () => {
    it('should convert "--" to "00"', () => {
      expect(normalizeGenotypeForFormat('--', 'ancestry')).toBe('00')
    })

    it('should handle whitespace around "--"', () => {
      expect(normalizeGenotypeForFormat(' -- ', 'ancestry')).toBe('00')
    })

    it('should leave other genotypes unchanged', () => {
      expect(normalizeGenotypeForFormat('AA', 'ancestry')).toBe('AA')
      expect(normalizeGenotypeForFormat('AT', 'ancestry')).toBe('AT')
      expect(normalizeGenotypeForFormat('CG', 'ancestry')).toBe('CG')
      expect(normalizeGenotypeForFormat('00', 'ancestry')).toBe('00')
      expect(normalizeGenotypeForFormat('0 0', 'ancestry')).toBe('0 0')
      expect(normalizeGenotypeForFormat('DD', 'ancestry')).toBe('DD')
      expect(normalizeGenotypeForFormat('II', 'ancestry')).toBe('II')
    })
  })
})

describe('parseAncestryFileAsync', () => {
  it('should parse ancestry file asynchronously with same results as sync version', async () => {
    const syncResult = parseAncestryFile(ANCESTRY_SAMPLE, 1)
    const asyncResult = await parseAncestryFileAsync(ANCESTRY_SAMPLE, 1)

    expect(asyncResult.snps).toEqual(syncResult.snps)
    expect(asyncResult.errors).toEqual(syncResult.errors)
    expect(asyncResult.format).toBe('ancestry')
  })

  it('should handle large files with batching', async () => {
    // Create a large file with 10,000 SNPs
    const header = `#AncestryDNA raw data download
rsid	chromosome	position	allele1	allele2
`
    const snpLines = Array.from({ length: 10000 }, (_, i) => `rs${i}\t1\t${1000 + i}\tA\tT`).join(
      '\n'
    )
    const largeFile = header + snpLines

    const result = await parseAncestryFileAsync(largeFile, 1)

    expect(result.snps).toHaveLength(10000)
    expect(result.format).toBe('ancestry')
    expect(result.errors).toHaveLength(0)
  })

  it('should validate and report errors asynchronously', async () => {
    const invalidContent = `#AncestryDNA raw data download
rsid	chromosome	position	allele1	allele2
rs123	1	100	A	T
rs456	99	200	C	G
rs789	1	300	X	Y`

    const result = await parseAncestryFileAsync(invalidContent, 1)

    expect(result.snps).toHaveLength(1) // Only first SNP is valid
    expect(result.errors).toHaveLength(2)
    expect(result.errors[0].reason).toContain('Invalid chromosome')
    expect(result.errors[1].reason).toContain('Invalid genotype')
  })

  it('should handle different chromosomes asynchronously', async () => {
    const content = `#AncestryDNA raw data download
rsid	chromosome	position	allele1	allele2
rs1	1	100	A	T
rs2	X	200	C	G
rs3	Y	300	G	G
rs4	MT	400	T	T
rs5	23	500	A	A`

    const result = await parseAncestryFileAsync(content, 1)

    expect(result.snps).toHaveLength(5)
    expect(result.snps.map(s => s.chromosome)).toEqual(['1', 'X', 'Y', 'MT', '23'])
  })
})

describe('parseMyHeritageFileAsync', () => {
  it('should parse MyHeritage file asynchronously with same results as sync version', async () => {
    const syncResult = parseMyHeritageFile(MYHERITAGE_SAMPLE, 1)
    const asyncResult = await parseMyHeritageFileAsync(MYHERITAGE_SAMPLE, 1)

    expect(asyncResult.snps).toEqual(syncResult.snps)
    expect(asyncResult.errors).toEqual(syncResult.errors)
    expect(asyncResult.format).toBe('myheritage')
  })

  it('should handle large files with batching', async () => {
    // Create a large file with 10,000 SNPs
    const header = `##fileformat=MyHeritage
##format=MHv1.0
RSID,CHROMOSOME,POSITION,RESULT
`
    const snpLines = Array.from(
      { length: 10000 },
      (_, i) => `"rs${i}","1","${1000 + i}","AT"`
    ).join('\n')
    const largeFile = header + snpLines

    const result = await parseMyHeritageFileAsync(largeFile, 1)

    expect(result.snps).toHaveLength(10000)
    expect(result.format).toBe('myheritage')
    expect(result.errors).toHaveLength(0)
  })

  it('should validate and report errors asynchronously', async () => {
    const invalidContent = `##fileformat=MyHeritage
RSID,CHROMOSOME,POSITION,RESULT
"rs123","1","100","AT"
"rs456","99","200","CG"
"rs789","1","300","XY"`

    const result = await parseMyHeritageFileAsync(invalidContent, 1)

    expect(result.snps).toHaveLength(1) // Only first SNP is valid
    expect(result.errors).toHaveLength(2)
    expect(result.errors[0].reason).toContain('Invalid chromosome')
    expect(result.errors[1].reason).toContain('Invalid genotype')
  })

  it('should handle different chromosomes asynchronously', async () => {
    const content = `##fileformat=MyHeritage
RSID,CHROMOSOME,POSITION,RESULT
"rs1","1","100","AT"
"rs2","X","200","CG"
"rs3","Y","300","GG"
"rs4","MT","400","TT"`

    const result = await parseMyHeritageFileAsync(content, 1)

    expect(result.snps).toHaveLength(4)
    expect(result.snps.map(s => s.chromosome)).toEqual(['1', 'X', 'Y', 'MT'])
  })

  it('should handle quoted CSV fields asynchronously', async () => {
    const content = `##fileformat=MyHeritage
RSID,CHROMOSOME,POSITION,RESULT
"rs3131972","1","752721","GG"
"rs114525117","1","759036","GG"`

    const result = await parseMyHeritageFileAsync(content, 1)

    expect(result.snps).toHaveLength(2)
    expect(result.snps[0].rsid).toBe('rs3131972')
    expect(result.snps[0].genotype).toBe('GG')
  })
})

describe('parseLivingDNAFile', () => {
  it('should parse valid LivingDNA file', () => {
    const result = parseLivingDNAFile(LIVINGDNA_SAMPLE, 1)

    expect(result.snps).toHaveLength(5)
    expect(result.format).toBe('livingdna')
    expect(result.chip).toBe('Sirius')
    expect(result.errors).toHaveLength(0)

    expect(result.snps[0].rsid).toBe('rs3131972')
    expect(result.snps[0].chromosome).toBe('1')
    expect(result.snps[0].genotype).toBe('AG')
  })

  it('should handle AX-* identifiers correctly', () => {
    const result = parseLivingDNAFile(LIVINGDNA_SAMPLE, 1)

    const axSnp = result.snps.find(s => s.rsid.startsWith('AX-'))
    expect(axSnp).toBeDefined()
    expect(axSnp?.rsid).toBe('AX-33748877')
    expect(axSnp?.genotype).toBe('CT')
  })

  it('should skip comment lines', () => {
    const result = parseLivingDNAFile(LIVINGDNA_SAMPLE, 1)

    // Should not count comment lines as errors
    expect(result.errors).toHaveLength(0)
  })

  it('should validate chromosomes', () => {
    const invalidContent = `# Living DNA
# rsid chromosome position genotype
rs123 99 100 AT`

    const result = parseLivingDNAFile(invalidContent, 1)

    expect(result.snps).toHaveLength(0)
    expect(result.errors).toHaveLength(1)
    expect(result.errors[0].reason).toContain('Invalid chromosome')
  })

  it('should validate genotypes', () => {
    const invalidContent = `# Living DNA
# rsid chromosome position genotype
rs123 1 100 XY`

    const result = parseLivingDNAFile(invalidContent, 1)

    expect(result.snps).toHaveLength(0)
    expect(result.errors).toHaveLength(1)
    expect(result.errors[0].reason).toContain('Invalid genotype')
  })

  it('should handle missing fields', () => {
    const invalidContent = `# Living DNA
# rsid chromosome position genotype
rs123 1`

    const result = parseLivingDNAFile(invalidContent, 1)

    expect(result.snps).toHaveLength(0)
    expect(result.errors).toHaveLength(1)
    expect(result.errors[0].reason).toContain('Insufficient columns')
  })
})

describe('parseLivingDNAFileAsync', () => {
  it('should parse LivingDNA file asynchronously', async () => {
    const result = await parseLivingDNAFileAsync(LIVINGDNA_SAMPLE, 1)

    expect(result.snps).toHaveLength(5)
    expect(result.format).toBe('livingdna')
    expect(result.chip).toBe('Sirius')
    expect(result.errors).toHaveLength(0)
  })

  it('should report progress with large dataset', async () => {
    // Create a large sample with 10000 lines to trigger progress reporting
    const largeLines = ['# Living DNA\n# rsid chromosome position genotype']
    for (let i = 0; i < 10000; i++) {
      largeLines.push(`rs${i} 1 ${i * 100} AT`)
    }
    const largeSample = largeLines.join('\n')

    const progressValues: number[] = []
    await parseLivingDNAFileAsync(largeSample, 1, p => progressValues.push(p))

    expect(progressValues.length).toBeGreaterThan(0)
  })
})

describe('mergeSnpsAsync', () => {
  const defaultOptions = { preferredFile: 1 as const, fillMissing: true }

  it('should merge SNPs asynchronously with same results as sync version', async () => {
    const file1 = parseAncestryFile(ANCESTRY_SAMPLE, 1)
    const file2 = parseMyHeritageFile(MYHERITAGE_SAMPLE, 2)

    const syncResult = mergeSnps(file1.snps, file2.snps, defaultOptions)
    const asyncResult = await mergeSnpsAsync(file1.snps, file2.snps, defaultOptions)

    expect(asyncResult.mergedSnps).toEqual(syncResult.mergedSnps)
    expect(asyncResult.conflicts).toEqual(syncResult.conflicts)
    expect(asyncResult.skippedRows).toEqual(syncResult.skippedRows)
  })

  it('should handle large datasets with progress reporting', async () => {
    // Create large datasets
    const file1Snps = Array.from({ length: 10000 }, (_, i) => ({
      rsid: `rs${i}`,
      chromosome: '1',
      position: `${1000 + i}`,
      genotype: 'AT',
      sourceFile: 1 as const,
    }))

    const file2Snps = Array.from({ length: 10000 }, (_, i) => ({
      rsid: `rs${i + 5000}`,
      chromosome: '1',
      position: `${6000 + i}`,
      genotype: 'CG',
      sourceFile: 2 as const,
    }))

    const progressUpdates: number[] = []
    const result = await mergeSnpsAsync(file1Snps, file2Snps, defaultOptions, (p: number) => {
      progressUpdates.push(p)
    })

    expect(result.mergedSnps).toHaveLength(15000)
    expect(progressUpdates.length).toBeGreaterThan(0)
    expect(progressUpdates[progressUpdates.length - 1]).toBe(100)
  })

  it('should detect conflicts asynchronously', async () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AT', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'GG', sourceFile: 2 as const },
    ]

    const result = await mergeSnpsAsync(file1Snps, file2Snps, {
      preferredFile: 1,
      fillMissing: false,
    })

    expect(result.mergedSnps).toHaveLength(1)
    expect(result.conflicts).toHaveLength(1)
    expect(result.conflicts[0].rsid).toBe('rs123')
    expect(result.conflicts[0].file1Genotype).toBe('AT')
    expect(result.conflicts[0].file2Genotype).toBe('GG')
    expect(result.conflicts[0].chosenGenotype).toBe('AT')
    expect(result.conflicts[0].resolutionReason).toBe('Preferred File 1')
  })

  it('should fill missing values asynchronously when enabled', async () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: '--', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AT', sourceFile: 2 as const },
    ]

    const result = await mergeSnpsAsync(file1Snps, file2Snps, {
      preferredFile: 1,
      fillMissing: true,
    })

    expect(result.mergedSnps[0].genotype).toBe('AT')
    expect(result.conflicts).toHaveLength(1)
    expect(result.conflicts[0].resolutionReason).toBe('Filled Missing from File 2')
  })

  it('should not fill missing values asynchronously when disabled', async () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: '--', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AT', sourceFile: 2 as const },
    ]

    const result = await mergeSnpsAsync(file1Snps, file2Snps, {
      preferredFile: 1,
      fillMissing: false,
    })

    expect(result.mergedSnps[0].genotype).toBe('--')
    expect(result.conflicts).toHaveLength(1)
    expect(result.conflicts[0].resolutionReason).toBe('Preferred File 1')
  })

  it('should prioritize preferred file asynchronously', async () => {
    const file1Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AT', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'GG', sourceFile: 2 as const },
    ]

    const result = await mergeSnpsAsync(file1Snps, file2Snps, {
      preferredFile: 2,
      fillMissing: false,
    })

    expect(result.mergedSnps[0].genotype).toBe('GG')
    expect(result.conflicts[0].resolutionReason).toBe('Preferred File 2')
  })

  it('should sort merged SNPs asynchronously', async () => {
    const file1Snps = [
      { rsid: 'rs3', chromosome: '2', position: '300', genotype: 'AT', sourceFile: 1 as const },
      { rsid: 'rs1', chromosome: '1', position: '100', genotype: 'AT', sourceFile: 1 as const },
    ]
    const file2Snps = [
      { rsid: 'rs2', chromosome: '1', position: '200', genotype: 'GG', sourceFile: 2 as const },
    ]

    const result = await mergeSnpsAsync(file1Snps, file2Snps, defaultOptions)

    expect(result.mergedSnps).toHaveLength(3)
    expect(result.mergedSnps[0].rsid).toBe('rs1')
    expect(result.mergedSnps[1].rsid).toBe('rs2')
    expect(result.mergedSnps[2].rsid).toBe('rs3')
  })

  it('should yield to main thread during processing', async () => {
    // Create dataset large enough to trigger yielding (> 5000 items)
    const file1Snps = Array.from({ length: 6000 }, (_, i) => ({
      rsid: `rs${i}`,
      chromosome: '1',
      position: `${1000 + i}`,
      genotype: 'AT',
      sourceFile: 1 as const,
    }))

    const file2Snps = Array.from({ length: 6000 }, (_, i) => ({
      rsid: `rs${i + 6000}`,
      chromosome: '1',
      position: `${7000 + i}`,
      genotype: 'CG',
      sourceFile: 2 as const,
    }))

    const startTime = Date.now()
    const result = await mergeSnpsAsync(file1Snps, file2Snps, defaultOptions)
    const endTime = Date.now()

    expect(result.mergedSnps).toHaveLength(12000)
    // Should complete in reasonable time (async processing should be fast)
    expect(endTime - startTime).toBeLessThan(2000)
  })
})
