// Shared test fixtures for DNA parser tests

export const ANCESTRY_SAMPLE = `#AncestryDNA raw data download
#This file was generated by AncestryDNA at: 01/17/2026 16:39:45 UTC
rsid	chromosome	position	allele1	allele2
rs3131972	1	752721	G	G
rs114525117	1	759036	G	G
rs11240777	1	798959	G	G
rs4475691	1	846808	T	C
rs7537756	1	854250	A	G`

export const MYHERITAGE_SAMPLE = `##fileformat=MyHeritage
##format=MHv1.0
##chip=GSA
RSID,CHROMOSOME,POSITION,RESULT
"rs3131972","1","752721","GG"
"rs114525117","1","759036","GG"
"rs11240777","1","798959","GG"
"rs4475691","1","846808","CT"
"rs2341354","1","918573","AG"`

export const LIVINGDNA_SAMPLE = `# Living DNA customer genotype data download file version: 1.1.0
# File creation date: 1-24-2025
# Genotype chip: Sirius
# The content of this file is subject to updates and changes depending on the time of download.
# Human Genome Reference Build 37 (GRCh37.p13).
# Genotypes are presented on the forward strand.
#
# rsid	chromosome	position	genotype
rs3131972	1	752721	AG
rs114525117	1	759036	GG
rs141175086	1	780397	CC
AX-33748877	22	51162850	CT
rs143357798	22	51193012	CC`
