import { describe, it, expect } from 'vitest'
import { generateAncestryCsv } from '../ancestry'

describe('generateAncestryCsv', () => {
  it('should generate valid Ancestry TXT format', async () => {
    const snps = [
      { rsid: 'rs123', chromosome: '1', position: '100', genotype: 'AA', sourceFile: 1 as const },
    ]

    const tsv = generateAncestryCsv(snps)

    expect(tsv).toContain('#AncestryDNA merged data')
    expect(tsv).toContain('rsid\tchromosome\tposition\tallele1\tallele2')
    expect(tsv).toContain('rs123\t1\t100\tA\tA')
  })

  it('should convert chromosomes to Ancestry numeric format', async () => {
    const snps = [
      { rsid: 'rs1', chromosome: 'X', position: '100', genotype: 'AA', sourceFile: 1 as const },
      { rsid: 'rs2', chromosome: 'Y', position: '200', genotype: 'TT', sourceFile: 1 as const },
      { rsid: 'rs3', chromosome: 'XY', position: '300', genotype: 'CC', sourceFile: 1 as const },
      { rsid: 'rs4', chromosome: 'MT', position: '400', genotype: 'GG', sourceFile: 1 as const },
    ]

    const tsv = generateAncestryCsv(snps)

    expect(tsv).toContain('rs1\t23\t100\tA\tA') // X → 23
    expect(tsv).toContain('rs2\t24\t200\tT\tT') // Y → 24
    expect(tsv).toContain('rs3\t25\t300\tC\tC') // XY → 25
    expect(tsv).toContain('rs4\t26\t400\tG\tG') // MT → 26
  })

  it('should split genotype into two alleles', async () => {
    const snps = [
      { rsid: 'rs456', chromosome: '2', position: '200', genotype: 'AC', sourceFile: 1 as const },
    ]

    const tsv = generateAncestryCsv(snps)

    expect(tsv).toContain('rs456\t2\t200\tA\tC')
  })

  it('should include timestamp in header', async () => {
    const tsv = generateAncestryCsv([])
    expect(tsv).toMatch(/#Generated by MergeDNA at:.*UTC/)
  })
})
